### PR TITLE
Added Bulgarian translation

### PR DESCRIPTION
**Pull request by twlvnn**
This request includes the bulgarian translation for Lock. Please make sure I added the language code to the build process correctly.

### CODE REVIEW

**Comment by konstantintutsch** [comment]
Great work! Could you translate the new strings from version 0.5.0?

You can run this command to update `bg.po` to include the new strings:

```
just translate
```

_just, meson and gettext need to be installed for this_

**Comment by twlvnn** [comment]
I'm having some difficulty with that sadly, I ran the command but got this:

```bash
meson compile -C _meson com.konstantintutsch.Lock-pot

ERROR: Current directory is not a meson build directory: `/home/me/Проекти/Lock/_meson`.
Please specify a valid build dir or change the working directory to it.
It is also possible that the build directory was generated with an old
meson version. Please regenerate it in this case.
error: Recipe `translate` failed on line 9 with exit code 1
```

I tried rebuilding the project but then I got other errors with the dependencies not installing my computer cant even fetch the remotes for flatpak/gnome (which I also get in every other project even when trying with Builder, so its something on my end that I have to fix). I'm fine with also updating it next week or whenever the POT file is updated, im not in a rush.

**Comment by twlvnn** [comment]
Nothing is simple on my computer 🙃:

```terminal
The Meson build system
Version: 1.5.1
Source dir: /home/me/Проекти/Lock
Build dir: /home/me/Проекти/Lock/_meson
Build type: native build
Project name: Lock
Project version: 0.4.1

meson.build:5:0: ERROR: Unable to detect linker for compiler `cc -Wl,--version`
stdout: ГНУ свързваща програма version 2.43.1-2.fc41
Авторско право: 2024 Фондация за свободен софтуер
Тази програма е свободен софтуер: можете да я разпространявате под условията
на Всеобщ Публичен Лиценз ГНУ версия 3 или по ваш избор, следваща версия.
Тази програма е без гаранции.

stderr: collect2 version 14.2.1 20240912 (Red Hat 14.2.1-3)
/usr/bin/ld -plugin /usr/libexec/gcc/x86_64-redhat-linux/14/liblto_plugin.so -plugin-opt=/usr/libexec/gcc/x86_64-redhat-linux/14/lto-wrapper -plugin-opt=-fresolution=/tmp/ccsjwrJQ.res -plugin-opt=-pass-through=-lgcc -plugin-opt=-pass-through=-lgcc_s -plugin-opt=-pass-through=-lc -plugin-opt=-pass-through=-lgcc -plugin-opt=-pass-through=-lgcc_s --build-id --no-add-needed --eh-frame-hdr --hash-style=gnu -m elf_x86_64 -dynamic-linker /lib64/ld-linux-x86-64.so.2 /usr/lib/gcc/x86_64-redhat-linux/14/../../../../lib64/crt1.o /usr/lib/gcc/x86_64-redhat-linux/14/../../../../lib64/crti.o /usr/lib/gcc/x86_64-redhat-linux/14/crtbegin.o -L/usr/lib/gcc/x86_64-redhat-linux/14 -L/usr/lib/gcc/x86_64-redhat-linux/14/../../../../lib64 -L/lib/../lib64 -L/usr/lib/../lib64 -L/usr/lib/gcc/x86_64-redhat-linux/14/../../.. --version -lgcc --push-state --as-needed -lgcc_s --pop-state -lc -lgcc --push-state --as-needed -lgcc_s --pop-state /usr/lib/gcc/x86_64-redhat-linux/14/crtend.o /usr/lib/gcc/x86_64-redhat-linux/14/../../../../lib64/crtn.o


A full log can be found at /home/me/Проекти/Lock/_meson/meson-logs/meson-log.txt
```

Feel free to leave it as it.. I can come back and update the translation later on before my dignity isn't lost completely here

**Comment by konstantintutsch** [comment]
git pull should work though

```
git reset --hard HEAD # discard changes by build system
git pull
```

**Comment by konstantintutsch** [comment]
That force push is fine, just a PR ;)

**Comment by twlvnn** [comment]
I think its good now, thanks for the help 😅

**Comment by konstantintutsch** [comment]
🎉

**Pull request merged**
